### ISSUE TITLE
Drafting the last player in a draft with depth charts has an error and gets stuck on "working".

### ISSUE THREAD

**Issue by zo0o0ot** [mattheworres/phpdraft#41]
I was able to reproduce this issue on both https://phpdraft.com/ and https://leagify.me/

Steps to reproduce:

- Create a league with depth charts.
- Start the draft
- Select players. All but the last should work fine.
- The last player will be correctly inserted into the database, but an error will happen on a SELECT statement which comes up on an Angular popup.
- Refreshing the page makes the "Working" pop-up go away, and the draft seems to have all of the correct players on the correct teams.

More information available here:
https://github.com/zo0o0ot/phpdraft-leagify/issues/2

**Comment by mattheworres** [comment]
Hmmm, this looks like it might be driven by #38 - the error from MySQL seems to indicate an issue with the Group By.

This isn't "duplicate" though, as I didnt realize this was a show-stopper. I'll try and get this patched up before the 2.2 changes officially make it out.

**Comment by mattheworres** [comment]
@zo0o0ot looks like I may have come across this before? See: http://stackoverflow.com/a/36033983/324527 (it's in the INSTALL.md directions, and I'm working through rewriting them for the 2.2 changes).

My MySQL server must have restarted since I last applied that. See Vincent Pazeller's comments below the answer as he answers his own question about persisting the changes.

I'll investigate whether this is a valuable fix, or if I should investigate changing the query altogether to avoid this issue.

**Comment by mattheworres** [comment]
@zo0o0ot take a look here for a fix in DraftStatsRepository.php: https://github.com/mattheworres/phpdraft/commit/a362f8123515998e4dbb8f22ec888689ab46d023

I should have a new release up with all of the deploy/DB migrations code for 2.2 sometime this week.

**Comment by mattheworres** [comment]
2.2.0 is live: https://github.com/mattheworres/phpdraft/releases/tag/2.2.0
