### ISSUE TITLE
Issues following openshift install instructions.

### ISSUE THREAD

**Issue by zo0o0ot** [mattheworres/phpdraft#7]
OK, I have some feedback on the openshift install instructions.

At the end, I got stuck in a redirect loop instead of success.

`This webpage has a redirect loop`

`ERR_TOO_MANY_REDIRECTS`

Notes:
+ The initialize script worked fine in phpmyadmin
+ I ended up creating a mailgun account.  We might want to include directions on how to verify email from an openshift app in mailgun.
+ in Linux, I think I needed to run `sudo npm install`
+ bower install didn't appear to have any output for me.
+ You should list gulp as one of the requirements for installation.
+ I didn't have a `/js` folder in my install.  Did I miss something in the process of converting the files from coffeescript?  I'm new to coffeescript.
+ I couldn't find `js/config.js` so I tried editing `api/config/dev.json` and `api/config/dev.json` since they appeared to contain similar information.
+  there was no `fonts/` directory.  I noticed that it was listed in the .gitignore file.
+ the only place I could find a css/ directory to copy was in app/css/.
+ Lacking /js and /fonts, I tried adding /gulp, /app, and /node_modules to the openshift ssh git project, instead.  It didn't end well.

I'm going to delete my openshift instance and try again soon.  Let me know if I've missed anything or done anything wrong.

**Comment by mattheworres** [comment]
Great questions! Some of these are issues I'll need to fix explicitly, and others I'll just need to clarify. I'll run through these later when I have the time - but the issue of redirects is with HTTPS. I can't quite get this one figured out, I flip flopped between enabling/disabling it and it seems to be recurring when the browser client has no cache. Essentially both your JS config file, .htaccess and appsettings.php have to all point to/use either HTTP or HTTPS. If one or more of them are out of whack, the app ends up in an infinite redirect loop.

Leaning towards just disabling HTTPs for the purpose of an OpenShift deployment.

**Comment by zo0o0ot** [comment]
I figured that might have been the issue.  Fair enough,  I'll follow along with either decision on the HTTP(S) front.

**Comment by zo0o0ot** [comment]
Another clarifying question: do you intend for people to start from the zip file that represents the 2.0.1 release, or a clone of the repo?  I cloned the repo.

**Comment by mattheworres** [comment]
Let me see if I can provide answers/comments to your observations (much appreciated, by the way):

- _I ended up creating a mailgun account. We might want to include directions on how to verify email from an openshift app in mailgun_ How to verify email? You mean the email account you sign up with? Or verify that it works?
- _in Linux, I think I needed to run sudo npm install_ This is true for global installs (`npm install [package] -g`, like `bower`), but in most instances this should be fine as it's just downloading files into the local `node_modules` folder. Regardless, I will update the docs accordingly.
- _bower install didn't appear to have any output for me._ That sounds about right. NPM is a chatty Cathy and bower is more the silent type IIRC
- _You should list gulp as one of the requirements for installation._ Nailed it here. I'll update this.
-_I didn't have a /js folder in my install. Did I miss something in the process of converting the files from coffeescript? I'm new to coffeescript._ It is. The js, css and fonts folders will all appear through the gulp build process, essentially building whatever is needed out of the /app folder and placing it where it goes for distribution.
- _I couldn't find js/config.js so I tried editing api/config/dev.json and api/config/dev.json since they appeared to contain similar information_ Yes. The name of the file directly corresponds to the name you pass the `--env=` option to `gulp build`. To make installs from the ZIP easier, I also split this JS out into its own file in the `js` folder so people wouldnt need to sift through minified garbage.
- _there was no fonts/ directory. I noticed that it was listed in the .gitignore file_ Yep - another result of the Gulp build process
_the only place I could find a css/ directory to copy was in app/css/_ Gulp build process, too. I ignore `js`, `css` and `fonts` since they are just processed versions of the source files in `app`, but with extra niceness like being concatenated into single files, and extraneous whitespace removed (both for network speediness).
_Lacking /js and /fonts, I tried adding /gulp, /app, and /node_modules to the openshift ssh git project, instead. It didn't end well._ Hmm. Yes, unfortunately node_modules is quite hefty, and is merely an artifact of the build process. Gulp will grab whatever it needs from both node_modules and bower_components and slams it into `js/vendor.js` (hence why that file is gargantuan).

So, my thinking in writing the OpenShift install with the repo clone as a starting point was that the tricky Composer step that I got stuck on (because you deploy your code to OpenShift, the `silex` folder in `vendor` ends up being empty, so the API is dead), I thought it would be easier. But I was wrong -- the tricky thing about build toolchains are that they're vastly different from org to org and project to project, and it'd be unfair for me to expect most folks to easily get through that. I should be able to release a proper ZIP file that will work on new installs, and I will update the instructions to be of more help.

This is superb feedback, thank you for being such a good sport and reporting back!

**Comment by zo0o0ot** [comment]
No problem.  There are worse situations than giving feedback and getting a reply, documentation, and better code as a result.

**Comment by zo0o0ot** [comment]
One other question, is it necessary to run `npm install -g coffee-script` or `npm install -g coffeescript-compiler`? I'm not sure if either of those were installed during my effort yesterday.

**Comment by zo0o0ot** [comment]
About the mailgun verification procedure, it looks like there is usually some sort of verification that needs to be performed.  I know that mandrill is a stickler about this.  You need to prove that you can receive an email sent from that domain in order for it to function correctly.  I ended up finding better dev walkthroughs for mailgun (such as http://stackoverflow.com/questions/23064765/cant-send-email-through-openshift), so I went with that even though I had a mandrill account, I created a new mailgun account for this.

In mailgun, it looks like the domain is listed as "unverified", but it isn't as finicky about needing proof of email, as far as I can tell.

**Comment by mattheworres** [comment]
@zo0o0ot no, there shouldn't be a need to install coffee-script globally via npm. There's a package listed in the project's `package.json` called `gulp-coffee` that provides the Coffeescript functionality needed to build the project.

As for the Mailgun verification - yes, I was worried about that as well but they seem less restrictive on that front. I also figured that'd be outside of the scope of this tutorial to handle things like that - I was able to send account verification emails from the get-go with Mailgun, which was very nice.

I updated the ZIP contained on the 2.0.1 release, so you may be able to download it and follow the newly updated OpenShift deployment instructions - I rewrote them to assume using the ZIP instead of manually building the project.

Let me know how it goes!

**Comment by zo0o0ot** [comment]
I'm a lot closer than I used to be, that's for sure!

I got the page to load!

However, I've been having some issues getting the API to respond appropriately.  To start, I used http configuration in my config files.  Here are the console errors that happen with that configuration:

![httpconfig](https://cloud.githubusercontent.com/assets/876146/12878133/c23f6dba-cde4-11e5-8c09-9550d63d4b4e.png)

Given the apparent openshift preference of https, I decided to go with it and switch my config files over to refer to https.

It seems to load better, but when trying to add a user, I still get some issues (which are noticed and notified via the frontend via angular popups, unlike the original http config)
![httpsenabled](https://cloud.githubusercontent.com/assets/876146/12878155/2a7bce96-cde5-11e5-9a3a-6b7379f6a450.png)

I tried rebooting the server, but the problem remained.

We're closer than we were before!  Woo!

**Comment by mattheworres** [comment]
The one thing I found is that for some reason the `.htaccess` does not forward properly for the HTTPS setting - so for OpenShift installs disabling it seems to be the only option. So make sure the URLs in `appsettings.php` use `http://` only, and also make sure `config.js` also uses only `http://` too. I also found that browsers cache a LOT here, so try and make sure to un-cache everything client side. When in doubt, try a separate browser altogether or a different computer to see if the issue persists).

**Comment by zo0o0ot** [comment]
Here's my results from using a different browser (Firefox this time).

I'm getting the page, but the API calls are returning 404.

![404-api-register](https://cloud.githubusercontent.com/assets/876146/12907632/36daeac2-ceb3-11e5-8d5c-13fc115926d0.png)


Is there anything set up like nelmio/swagger or another api sandbox/checker?  It seems like the site is up but the API is down.

**Comment by mattheworres** [comment]
That's bizarre - even when I hit my issue with the Silex dependency not being uploaded, the server returned a 500 error - 404 suggests that Apache doesn't even know where to look for it. Either the `.htaccess` is wrong (which I doubt - you've been editing it to change the HTTPS stuff, and it seems to be sorted out to have HTTPS disabled now) or the entire `/api` folder is missing. `.htaccess` more or less just tells Apache to route all calls that begin with `/api` to `api/bootstrap.php`, and from there Silex grabs it and handles it as necessary. Seems that there's a disconnect there.

Maybe delete the Openshift site and try again anew with the newest ZIP archive on the Releases page?

**Comment by zo0o0ot** [comment]
Before I delete and start over, I'll take another look at `.htaccess` --  I've been focusing mostly on `js/config.js` and `appsettings.php`, so maybe I forgot proper `.htaccess` settings in the shuffle.

**Comment by mattheworres** [comment]
@zo0o0ot yes - I was going to add go ahead and keep a copy of the appsettings.php as that won't change and it'll save you 15 or 20 minutes if you start over. Honestly you might not even need to delete the Openshift app, just download the ZIP, then delete the Openshift app repo directory contents (not the `.git` or `.openshift` folders though), then extract the ZIP contents in, and set your `appsettings.php` and `js/config.js` and `.htaccess` files as need be, then commit and push those changes back to Openshift.

This is supposed to be a lot easier, I swear! :smile:  You hit on a few odd edge cases and really helped me iron them out though, I think it should be straightforward from here on out.

**Comment by zo0o0ot** [comment]
I'm OK with hitting edge cases.  It smooths the path for everyone else.

**Comment by zo0o0ot** [comment]
Yep, it was the `.htaccess` file missing.  I commented out these two lines:

```
    #RewriteCond %{HTTPS} off
    #RewriteRule .* https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

Then I committed and pushed, and it started up.  Now, we're cooking with gas.  Next, I'm going to try to make my own league.  I'll see what I need to do to get that done.
